spring:
  mail:
    username: nevermore_sf@aliyun.com
    password: ll6984303
    host: smtp.aliyun.com
  rabbitmq:
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 1
        max-concurrency: 1
        retry:
          enabled: true

